name: petitparser_extras
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/guypeled76
author: guy.p <guypeled76@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  petitparser: ^2.4.0
  resource: ^2.1.6

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
